### ISSUE TITLE
granger2d should work for more than 2d data 

### ISSUE THREAD

**Issue by gherardovarando** [cmu-phil/causal-learn#12]
Problem: `granger_test_2d` will throw an error if applied to data with more than 2 variables (`d > 2`). 

I think that probably without the check below, the `granger_test_2d` method in the `Granger` class will work over data with more than 2 variables. 

https://github.com/cmu-phil/causal-learn/blob/6f297e743c462b4a2f8191250ea9ac03c288abf0/causallearn/search/Granger/Granger.py#L43

If this behavior is wanted maybe documentation should be changed, as doc is now it states that `granger_test_2d` will return matrices of pvalues and adjacency  and it accept `data (nxd)` as input.

**Comment by kunwuz** [comment]
Hi, thanks for the feedback. It is possible to do it in a pair-wise manner, but the false positive rate will be relatively high. So perhaps it is not recommended.

**Comment by gherardovarando** [comment]
sure, it makes sense. Then I suggest to change doc into something like:
```
      Granger causality test for two-dimensional time series
        Parameters:
        -----------
        data - 2d input data (nx2)
```

**Comment by kunwuz** [comment]
Thanks! I've updated the doc according to your suggestion.
