### ISSUE TITLE
How to transfer general graph into matirx

### ISSUE THREAD

**Issue by MAX00008888** [cmu-phil/causal-learn#22]

**Comment by MAX00008888** [comment]
@kunwuz 请问一下怎么把产生的general graph 转换成 matrix的形式

**Comment by kunwuz** [comment]
Hi, you could try to use G.graph (G is a general graph) to output a matrix (https://github.com/cmu-phil/causal-learn/blob/ed86eb7bac8973caaf758ed4bb2e6f5ec7f37850/causallearn/graph/GeneralGraph.py#L38). And the explanation of endpoints could be found here: https://github.com/cmu-phil/causal-learn/blob/main/causallearn/graph/Endpoint.py)

**Comment by MAX00008888** [comment]
Thank you soooo much!!!!!! @kunwuz

**Comment by kunwuz** [comment]
You are welcome!
