### ISSUE TITLE
Add cache for local score function for efficiency.

### ISSUE THREAD

**Issue by Howardhuang98** [cmu-phil/causal-learn#24]
Local score is calculated repeatly during search.  

Make the function `def local_score_BDeu(Data: ndarray, i: int, PAi: List[int], parameters=None) -> float:` cachable.  Strongly recommend to use functools.lru_cache, that is a efficient python built-in decorator. But it requires all parameters are hashable, currently they are not, e.g. ndarray.     

A commonly solution is to create a Score class to store data, and local score function only takes i, and parents tuple (now it is a list).

**Comment by kunwuz** [comment]
Thanks so much for your suggestion! We will look into it and try to find out a way to improve the efficiency accordingly.

**Comment by chenweiDelight** [comment]
@Howardhuang98  Thank you for your suggestion! We have added cache for the local score function. Please feel free to let us know if there are any other issues.

**Comment by kunwuz** [comment]
Thanks so much, @chenweiDelight ! Please feel free to reopen it if you have any further suggestions :)
