### ISSUE TITLE
score_g function

### ISSUE THREAD

**Issue by Yuchen0606** [cmu-phil/causal-learn#32]
I am not sure if the function "score_g" in causallearn.utils.GESUtils is designed to calculate the score of a causal graph given a specific dataset. But when I used it, I found when parameter "PA" is not empty list, it comes to an error "IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices".
I think the reason of the problem is the “PA” given by "score_g" does not match the parameter (PAi) request of local_score_BIC.
Much appreciate for your response.
![屏幕截图 2022-06-08 163326](https://user-images.githubusercontent.com/36750821/172571734-d3ae8955-d016-4833-8e0e-95b4818c65d0.png)
![屏幕截图 2022-06-08 163700](https://user-images.githubusercontent.com/36750821/172571798-d4628416-32e3-4bb4-99da-f24b6f4570ae.png)

**Comment by chenweiDelight** [comment]
Thank you very much for pointing out this issue. We have fixed this bug. 
Please feel free to let us know if there is any other problem.
