### ISSUE TITLE
Unresolved GIT confict

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/causal-learn#39]
I just checked out CL from the repository and noticed there is an unresolved conflict in 

https://github.com/cmu-phil/causal-learn/blob/main/tests/TestANM.py

Here:

<<<<<<< HEAD
    test.test_anm_simul()
    test.test_anm_pair()
=======
    test.test_anm_pair()
>>>>>>> 8443c497f18ad0894ca9e86790cc630631680cb0

**Comment by kunwuz** [comment]
Fixed. Thanks for catching this!
