### ISSUE TITLE
Add reference paper for implementation of granger lasso method

### ISSUE THREAD

**Issue by STLDR** [cmu-phil/causal-learn#45]
Hello everyone!

I want to use your library as part of an ongoing project, because I saw that you implemented a granger causality test for multi-dimensional time series called `granger_lasso`  ([docs](https://causal-learn.readthedocs.io/en/latest/search_methods_index/Granger%20causality/LinearGranger.html)).

I am curious based on which academic literature you implemented this method. There exist many papers who combine granger causality with some lasso regularization, so it is unclear for me why you implemented it that way.

It would be great if you can provide the reference paper here or, even better, update the documentation so other people can also benefit from this information.

Thank you very much in advanced.

**Comment by kunwuz** [comment]
Hi, thanks so much for your great suggestion. The [reference](https://academic.oup.com/bioinformatics/article/26/18/i517/205683?login=false) has been added to the [page](https://causal-learn.readthedocs.io/en/latest/search_methods_index/Granger%20causality/LinearGranger.html).

**Comment by STLDR** [comment]
Thank you for your quick reply.
I looked through the referenced paper and compared it to the code in the causal-learn repo. I have the impression that the description and the code do not really match. Also the code of the original R package and the causal-learn implementation seem to be quite different. Can you comment on that?

**Comment by aoqiz** [comment]
Hi, Stephan. Thanks for your question. 
We didn't follow their code exactly. Our implementation is a standard autoregressive model with lasso penalties. [This paper](https://www.andrewoarnold.com/frp781-arnold.pdf) might also give you some ideas on the implementation. Equation (3) in this paper is the objective of our implemented algorithm. The optimisation procedure might be different from the paper. Also, we used cross validation to select the L1 penalty weight.
