### ISSUE TITLE
pip install?

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/causal-learn#47]
Dumb question: Does pip install causal-learn grab the latest version from the repository, or do I need to grab the repository version and install that myself locally?

Thanks!

**Comment by kunwuz** [comment]
Thanks for raising this brilliant question. This is very important as it could help to make sure that our users are using the up-to-date version.

For `pip install causal-learn`, it will install the package we released to PyPI ([https://pypi.org/project/causal-learn/](https://pypi.org/project/causal-learn/)). However, we only do it when there have been significant updates to our package. So if users would like to use the most up-to-date one, it is more recommended to install it from the source (GitHub). At the same time, the version installed from PyPI should have most of the up-to-date features that significantly influence the functionality and performance, though generally not including the most recent commits.

**Comment by jdramsey** [comment]
Thanks for the clarification!
