### ISSUE TITLE
Please provide developing guidelines for outside contributors

### ISSUE THREAD

**Issue by limjcst** [cmu-phil/causal-learn#5]
When I tried to pass unittests in `tests/`, I got confused about how maintainers collect so many test cases.
Finally, I executed `python -m unittest discover -p "Test*.py"` under `tests/`, which I hope is the correct usage.

The tests first failed due to the lack of `pygam` (required by `CAMUV`) and `torch` (required by `PNL`), as I executed `python setup.py install` to install the requirements.
I thought that a simple patch in `setup.py` could solve this problem. But WAIT! What if the maintainers just want to make big packages like `torch` optional? It is so nice of you to think like that.
However, it would be better to document such packages somewhere, like in `README.md` or `setup.py`.

A general advice is to provide more information about how to participate in the development of this project in `README.md`. It would be better to provide executable commands in continuous integration configuration.

What's more, could the developing guidelines of this repository, if it already exists, change a little bit?
For example, `print` is widely used in this project. I find it annoying as a user like me cannot disable those messages. Could this project use the `logging` package with the `DEBUG` level instead?

**Comment by kunwuz** [comment]
First, thanks for your interest and very constructive suggestions!

Regarding the extra packages required for CAMUV and PNL, yes, we are working on getting rid of those dependencies. We will update it and let you know ASAP when those dependencies could be removed.

The 'causal-learn' is still under active development, so any suggestion is very welcome and will be appreciated a lot. For example, we will update a new version of FCI in the very near future, which runs much faster than the current version.

Regarding the developing guidelines, I completely agree with you. We will change it and modify the corresponding parts of the code to enhance the user experience. Also, if you would like to contribute to causal-learn, please feel free to create a pull request. And I'm always willing to chat about how to improve causal-learn or any issues. My email: yujiazh@cmu.edu.

Again, thanks for your interest in causal-learn :)

**Comment by limjcst** [comment]
Thanks for your fast response!

In term of the user experience, I find that [type hints](https://docs.python.org/3/library/typing.html) is useful, especially when the documentation is not clear.

**Comment by kunwuz** [comment]
Thanks for sharing!~ It is indeed useful.

**Comment by kunwuz** [comment]
> Thanks for your fast response!
> 
> In term of the user experience, I find that [type hints](https://docs.python.org/3/library/typing.html) is useful, especially when the documentation is not clear.

Hi, just a quick update on your previous suggestions. Regarding type-hint, @JarodYv has been making contributions on it :) Thanks, Jarod!
