### ISSUE TITLE
multi-threading support

### ISSUE THREAD

**Issue by lockmatrix** [cmu-phil/causal-learn#66]
I found algorithm takes a long time to run, maybe should add multi-threading support

**Comment by kunwuz** [comment]
Yes, you are totally right. At the same time, regarding some tests, the theoretical guarantees might not hold when being performed in a parallel manner. Please feel free to let us know if you have any proposals on adding multi-threading support, which will certainly be greatly appreciated :)

**Comment by lockmatrix** [comment]
I found on Macbook M2, fisherz can reach 550-600% CPU, is it a single thread algorithm?

**Comment by lockmatrix** [comment]
I find https://github.com/cmu-phil/tetrad which support multi-threading
