### ISSUE TITLE
Usage of KCI test

### ISSUE THREAD

**Issue by Peng0618** [cmu-phil/causal-learn#69]
I am interested in the KCI independence test function (causallearn.utils.cit.kci) and testing it now. 

In the test, the input "data" is set with a simple numpy data table and column indices  X Y are set as 1,2. However, after running the function, there is a TypeError ""str" object is not callable", as shown below. Does anyone know what is the cause of this problem , or show me with a correct example about this function's usage? Thank you.

![WeChat Image_20220824122322](https://user-images.githubusercontent.com/31668299/186489106-0054226d-ac4e-427c-aaf0-9cb9d0eefa41.jpg)

**Comment by kunwuz** [comment]
Thanks for reaching out. We just made a major refactor on our independence test functions and we haven't updated the corresponding parts of the document. For quick examples, you could try to refer [TestCIT.py](https://github.com/cmu-phil/causal-learn/blob/main/tests/TestCIT.py) and [TestCIT_KCI.py](https://github.com/cmu-phil/causal-learn/blob/main/tests/TestCIT_KCI.py). We will update the document ASAP. Please let us know if there are any further questions.

**Comment by Peng0618** [comment]
Thanks for you reply. Now it works!


<img width="462" alt="image" src="https://user-images.githubusercontent.com/31668299/186494388-d0e2f3e0-c626-49c1-ba3d-9a1aab218579.png">

**Comment by kunwuz** [comment]
Cool! Thanks :)
