### ISSUE TITLE
ImportError: cannot import name 'GIN' from 'causallearn.search.FCMBased' 

### ISSUE THREAD

**Issue by chengjun** [cmu-phil/causal-learn#70]
```
from causallearn.search.FCMBased.GIN.GIN import GIN
G, K = GIN(data)
```

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/var/folders/8b/hhnbt0nd4zsg2qhxc28q23w80000gn/T/ipykernel_52081/3662974966.py in <module>
----> 1 from causallearn.search.FCMBased import GIN
      2 G, K = GIN(data)

ImportError: cannot import name 'GIN' from 'causallearn.search.FCMBased' (/Users/datalab/github/causal-learn/causallearn/search/FCMBased/__init__.py)

**Comment by chenweiDelight** [comment]
Hi chengjun,

Thank you for your comment! Could you tell me which version you used?
We have moved the GIN to 'HiddenCausal'. So you can try to import GIN by 'from causallearn.search.HiddenCausal.GIN.GIN import GIN'.

Please let me know if there is any problem.

**Comment by kunwuz** [comment]
Hi, thanks for the question. We have just updated our document to make it consistent.

**Comment by kunwuz** [comment]
Hi, please feel free to let us know and reopen this issue if there is any further issue.
