### ISSUE TITLE
FCI algorithm with KCI testing method

### ISSUE THREAD

**Issue by Peng0618** [cmu-phil/causal-learn#73]
Hello, 

I am testing the fci algrithm and its defaul independence testing method is 'fisherz'. I tried to use the 'kci' testing method. But it shows:

TypeError: '(slice(None, None, None), [0])' is an invalid key.

So, is there any example about the fci algorithm with kci method? Thank you.

**Comment by MarkDana** [comment]
Thanks for reaching out. Could you please tell us your causal-learn version and the minimum code snippet that reproduces your issue?

Since `G, edges = fci(data, 'kci', 0.05, verbose=False)` should work.

**Comment by Peng0618** [comment]
Hi, the causal-learn version is 0.1.2.8. Thanks for your sample. I have solved it.

BTW, the kci testing is much slower than fisherz... But it is still a good choice.

**Comment by MarkDana** [comment]
Yep. kci is basically in O(n^3) time complexity, with n being the sample size.

The good thing is that kci is nonparametric, while fisherz only works for joint Gaussian.
