### ISSUE TITLE
Import Error during using

### ISSUE THREAD

**Issue by Ricardokevins** [cmu-phil/causal-learn#77]
I am a novice in this field, seek for help...

Operation:
pip install causal-learn(sucessfully)
touch a new file test.py(sucessfully)
copy testPC.py to test.py(sucessfully)
python3 test.py (encounter Error ：
```
(main) ➜  Test git:(main) ✗ python3 testC.py 
Traceback (most recent call last):
  File "testC.py", line 8, in <module>
    from causallearn.utils.cit import chisq, fisherz, gsq, kci, mv_fisherz, d_separation
ImportError: cannot import name 'd_separation' from 'causallearn.utils.cit' (/Users/sheshuaijie/app/miniconda3/envs/main/lib/python3.8/site-packages/causallearn/utils/cit.py)
```

Any Suggestion will be greatly appreciate!!!!

**Comment by MarkDana** [comment]
Hi @Ricardokevins. Which version of causal-learn are you using? This might be due to an outdated version. We'll release a latest one soon and please update to it. Thanks for identifying this :)

**Comment by kunwuz** [comment]
Hi, thanks for reaching out. We have just released a version on pypi. Could you please try 'pip install causal-learn==0.1.2.9' and run your scripts again?

**Comment by Ricardokevins** [comment]
> Hi, thanks for reaching out. We have just released a version on pypi. Could you please try 'pip install causal-learn==0.1.2.9' and run your scripts again?

Thank you for your immediate reply, I just tried and get new Error as follow

```
Traceback (most recent call last):
  File "ttt.py", line 12, in <module>
    from utils_simulate_data import simulate_discrete_data, simulate_linear_continuous_data
ModuleNotFoundError: No module named 'utils_simulate_data'
```

**Comment by Ricardokevins** [comment]
> Hi @Ricardokevins. Which version of causal-learn are you using? This might be due to an outdated version. We'll release a latest one soon and please update to it. Thanks for identifying this :)

I follow the below instruction and get a new error information

**Comment by Ricardokevins** [comment]
Thank you very much for your quick reply.
Problem fixed with your help
