### ISSUE TITLE
How to Visualize Casual Graph?

### ISSUE THREAD

**Issue by Ricardokevins** [cmu-phil/causal-learn#79]
Awesome work!
I just try to use TestDirectLiNGAM to get the casual graph on public dataset. And the result is interesting! Thank you for your work~     I am interested in visualizing the casual graph I got ( TestDirectLiNGAM method produce a adjacency_matrix_). Is there any operation to get a png which visualize the graph?
Aftering reading docs, i notice there is some Graph operations but no visualize2Graph Operation :(

**Comment by kunwuz** [comment]
Hi, perhaps you could try to refer to this [example](https://github.com/cmu-phil/causal-learn/blob/b49980d046607baaaa66ff8dc0ceb98452ab8616/tests/TestGraphVisualization.py#L43) to visualize it according to your matrix.
