### ISSUE TITLE
Does DAG2PAG supports selection variable?

### ISSUE THREAD

**Issue by lmz123321** [cmu-phil/causal-learn#80]
Hi, I hope to use the dag2pag function in the causal-learn lab, i.e., ```causallearn.utils.DAG2PAG```.

However, I notice in the [documentation](https://causal-learn.readthedocs.io/en/latest/utilities_index/Graph%20operations/DAG2PAG.html), this function only support add latent variables. 

Is there a way to add selection variables (maybe a custom change to the function) ?

Many thanks!

**Comment by chenweiDelight** [comment]
Hi, unfortunately, DAG2PAG doesn't support selection variables for now. We're not sure about the custom changes now, but we will try and see whether it's plausible. Thanks!
