### ISSUE TITLE
CD-NOD with independent change principle.

### ISSUE THREAD

**Issue by lmz123321** [cmu-phil/causal-learn#81]
Hi, thanks for your great work.

I hope to use CD-NOD phase 3, i.e., identifying directions with independent change principle.

However, I notice it is still not implemented (a TODO comment).

When do you plan to release these codes?

Many thanks.

**Comment by leizan** [comment]
Hi, I find that the author has also made a complete matlab version:
https://github.com/Biwei-Huang/Causal-Discovery-from-Nonstationary-Heterogeneous-Data
Hope that could help you.

**Comment by lmz123321** [comment]
Thanks a lot. I check the matlab code and it works fune.
