### ISSUE TITLE
On the development of PNL 

### ISSUE THREAD

**Issue by amir-rahnama** [cmu-phil/causal-learn#83]
When will the implementation of the PNL method be completed? I saw that development has stopped since Feb 18, 2022. What are the remaining parts of the algorithm that needs to be implemented precisely? Maybe I can help

**Comment by kunwuz** [comment]
Thanks for reaching out. We've been improving PNL and adding more tests during the past months. A new version has just been updated and please feel free to give it a try. Any questions are very welcome.
