### ISSUE TITLE
Orientation rules for FCI

### ISSUE THREAD

**Issue by jmaasch** [cmu-phil/causal-learn#88]
Hello,

Are the edge orientation rules for the FCI implementation taken from Zhang et al (2008)? This paper introduces additional orientation rules and proves their completeness. I am wondering if the entire set of orientation rules required for completeness are implemented in this package.

> 1. Zhang, J. On the completeness of orientation rules for causal discovery in the presence of latent confounders and selection bias. Artificial Intelligence 172, 1873–1896 (2008).

If not, from which citation(s) are the orientation rules taken?

Thanks!

**Comment by kunwuz** [comment]
Yes, exactly. The orientation rules follow those in the paper you referred to.

**Comment by kunwuz** [comment]
Sorry, I was wrong--it hasn't yet included R5-10 introduced in that paper.

**Comment by jmaasch** [comment]
Thank you for your diligence in following up! Are there plans to implement these rules?
