### ISSUE TITLE
Generalized score with mixed data

### ISSUE THREAD

**Issue by guyq1997** [cmu-phil/causal-learn#89]
hello,

i used generalized score to do GES on mixed data, which contains float and string types of data. But somehow it failed.
Is there any example for this situation?

Best Regards
Yuqiang

**Comment by kunwuz** [comment]
Hi Yuqiang, sorry we don't have any examples. Besides, I'm afraid that GES with the generalized score does not support string-type data without some type of preprocessing, which I'm not sure about yet. Thanks for your question.
